name             'plex'
maintainer       'Henry Muru Paenga'
maintainer_email 'meringu@gmail.com'
license          'All rights reserved'
description      'Installs/Configures plex'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.1'
supports         'ubuntu', '>= 10.04'
supports         'fedora', '>= 14'
supports         'centos', '>= 6'
supports         'redhat', '>= 6'
